### ISSUE TITLE
Change scroll physics to bouncing scroll physics

### ISSUE THREAD

**Issue by shatanikmahanty** [OpenCodeyard/ocyclient#3]
The bouncing scroll physics applies a bouncing effect to the scrolling behavior.

To complete this issue change the scroll physics property of scrollable elements in the project to BouncingScrollPhysics().

**Comment by karanpatel2329** [comment]
can you assign this issue to me?

**Comment by shatanikmahanty** [comment]
> can you assign this issue to me?

We are glad that you have decided to contribute to our repositories. Since you are the first one here, this issue will be assigned to you. We will start assigning issues from the 1st of October when Hacktoberfest starts. Happy coding.

Make sure you have completed the checklist

- [ ] Join our telegram for discussion: https://telegram.me/Open_Codeyard 
- [ ] Make sure you abide by the [Contributors Guideline](https://github.com/OpenCodeyard/ocyclient/blob/dev/CONTRIBUTING.md)
- [ ] Star this repo

**Comment by shatanikmahanty** [comment]
@karanpatel2329 Do you confirm to that you are still available to work on this issue? If yes please star this repo and respond here.

**Comment by karanpatel2329** [comment]
yes, I am will to work on this issue. Please assign to me.

**Comment by shatanikmahanty** [comment]
> Hey @shatanikmahanty , I would like to work on this issue

This issue was already claimed by @karanpatel2329. We will be adding many issues in this edition of Hacktoberfesr. Stay tuned!

**Comment by shatanikmahanty** [comment]
@karanpatel2329 just checking in if you are working on this. Please reply to this comment to mark your participation. Reach out to us on community channels if you face issue setting up the project

**Comment by shatanikmahanty** [comment]
@karanpatel2329 we are unassigning you due to inactivity

**Comment by Codesait** [comment]
Please let me quickly get this task done.
@shatanikmahanty

**Comment by shatanikmahanty** [comment]
@Codesait go ahead.

We are glad that you have decided to contribute to our repositories. 

Make sure you have completed the checklist

- [ ] Join our telegram for discussion: https://telegram.me/Open_Codeyard 
- [ ] Make sure you abide by the [Contributors Guideline](https://github.com/OpenCodeyard/ocyclient/blob/dev/CONTRIBUTING.md)
- [ ] Star this repo

**Comment by Codesait** [comment]
@shatanikmahanty is there any specific class you want this changes be applied.
Will love specifics. thanks

**Comment by Codesait** [comment]
So regarding this issue
 I have added the scroll physics to
 Home
 Profile
 Teams
 Projects
 About Us
 Member_vertical
 Member_horizontal
 
 Please if there are other specific places you need me to make this change, I will be glad to .

**Comment by shatanikmahanty** [comment]
@Codesait I think that covers it all. Please create a PR. I will review the changes and let you know.

**Comment by Codesait** [comment]
> @Codesait I think that covers it all. Please create a PR. I will review the changes and let you know.

Okay thanks

**Comment by shatanikmahanty** [comment]
Closing as completed
