### ISSUE TITLE
Add twitter icon button for team members

### ISSUE THREAD

**Issue by shatanikmahanty** [OpenCodeyard/ocyclient#5]
![image](https://user-images.githubusercontent.com/67138059/192704444-bc6c9962-2f7f-4c4b-a114-da5fba416daf.png)
![image](https://user-images.githubusercontent.com/67138059/192704555-f54c1651-fedc-4ce7-8c7d-13b73f961e9e.png)

There are two types of views for team members for www.opencodeyard.tech/teams

Horizontal view for larger screen resolutions
Vertical view for larger screen resolutions

Add Twitter Icon Button to both views by referring to the current social icon logic

**Comment by garvpatidar04** [comment]
Hello Sir,
Can you assign me this issue? I like to work on it.

**Comment by error707-persona** [comment]
Can you assign me this issue, I have worked on something similar previously and have knowledge od media queries to make responsive screens

**Comment by shatanikmahanty** [comment]
> Hello Sir,
> Can you assign me this issue? I like to work on it. 

We are glad that you have decided to contribute to our repositories. Since you are the first one here, this issue will be assigned to you. We will start assigning issues from the 1st of October when Hacktoberfest starts. Happy coding.

Make sure you have completed the checklist

- [ ] Join our telegram for discussion: https://telegram.me/Open_Codeyard 
- [ ] Make sure you abide by the [Contributors Guideline](https://github.com/OpenCodeyard/ocyclient/blob/dev/CONTRIBUTING.md)
- [ ] Star this repo

**Comment by shatanikmahanty** [comment]
> Can you assign me this issue, I have worked on something similar previously.

Sorry we couldn't assign the issue to you as they are on a first come first serve basis. Be rest assured we will be adding many issues in the coming days that are beginner friendly. Till then join our telegram group to stay tuned to further updates

**Comment by shatanikmahanty** [comment]
Nice work @garvpatidar04. Closing this as completed under PR #11

**Comment by garvpatidar04** [comment]
> Nice work @garvpatidar04. Closing this as completed under PR #11

Thank you. I’m so glad that I could contribute to this issue.
