### ISSUE TITLE
Add watchers count to project card

### ISSUE THREAD

**Issue by shatanikmahanty** [OpenCodeyard/ocyclient#7]
The home page project card shows stars, forks, and issues count.

![image](https://user-images.githubusercontent.com/67138059/193416955-0396f8f0-6819-4ee5-9859-80053af8f045.png)

![image](https://user-images.githubusercontent.com/67138059/193416970-cab242f7-917d-482a-9d7e-8dcf8c79f134.png)

GitHub Repos show watchers count. Add watchers count to the website as well.

project_mode.dart file in code already contains the backend logic. We need to integrate that with the UI.

Make sure to use font_awesome icons. Library is already installed in pubspec.yaml

**Comment by hemantwasthere** [comment]
Hey @shatanikmahanty, I would love to work on this issue

**Comment by shatanikmahanty** [comment]
> Hey @shatanikmahanty, I would love to work on this issue

@hemantwasthere, we are glad that you have decided to contribute to our repositories. Since you are the first one here, this issue will be assigned to you. We will start assigning issues from the 1st of October when Hacktoberfest starts. Happy coding.

Make sure you have completed the checklist

- [ ] Join our telegram for discussion: https://telegram.me/Open_Codeyard 
- [ ] Make sure you abide by the [Contributors Guideline](https://github.com/OpenCodeyard/ocyclient/blob/dev/CONTRIBUTING.md)
- [ ] Star this repo

**Comment by shatanikmahanty** [comment]
@hemantwasthere I have assigned the issue to you. Happy contributing!

**Comment by shatanikmahanty** [comment]
@hemantwasthere just checking in if you are working on this. Please reply to this comment to mark your participation. Reach out to us on community channels if you face issue setting up the project

**Comment by hemantwasthere** [comment]
Yeah i am working on this

**Comment by hemantwasthere** [comment]
@shatanikmahanty sorry bro, i am unable to resolve this issue

**Comment by shatanikmahanty** [comment]
> @shatanikmahanty sorry bro, i am unable to resolve this issue

Do you want me to unassign you?

**Comment by hemantwasthere** [comment]
> > @shatanikmahanty sorry bro, i am unable to resolve this issue
> 
> Do you want me to unassign you?

Yes, i already unassigned myself

**Comment by Rohit-RA-2020** [comment]
Hey, assign this to me
I can add this feature

**Comment by shatanikmahanty** [comment]
> Hey, assign this to me
> I can add this feature

I have assigned the issue to you. Happy contributing ❤️

**Comment by Rohit-RA-2020** [comment]
Just have a look, before I make a PR
![Screenshot 2022-10-09 214520](https://user-images.githubusercontent.com/53489549/194767693-c28f4c9f-7d8d-4b9d-8163-2b3193b1ddd0.png)

**Comment by shatanikmahanty** [comment]
> Just have a look, before I make a PR
> ![Screenshot 2022-10-09 214520](https://user-images.githubusercontent.com/53489549/194767693-c28f4c9f-7d8d-4b9d-8163-2b3193b1ddd0.png)
> 

Looks great @Rohit-RA-2020. Go ahead with the PR

**Comment by shatanikmahanty** [comment]
Nice work @Rohit-RA-2020. Closing this as completed under PR #16
